In [40]:
from PIL import Image
import numpy as np
import math

In [17]:
imagePath = "../images/example1.webp"
im = Image.open(imagePath)
print("Successfully loaded image!")
print("Image Size: ", im.size)

Successfully loaded image!
Image Size:  (1232, 928)


In [31]:
imArray = np.asarray(im).astype(int)
imArray = imArray[:480, :640]
print("Successfully loaded image into array!")
print("Pixel array dimensions: ", imArray.shape)
print(imArray)

Successfully loaded image into array!
Pixel array dimensions:  (480, 640, 3)
[[[ 87  84  76]
  [ 89  83  76]
  [ 90  82  76]
  ...
  [120 146 169]
  [120 146 167]
  [125 144 165]]

 [[ 89  83  76]
  [ 89  83  76]
  [ 92  81  76]
  ...
  [120 146 169]
  [120 146 167]
  [125 144 165]]

 [[ 90  82  76]
  [ 92  81  76]
  [ 92  81  76]
  ...
  [120 146 169]
  [120 146 169]
  [125 144 165]]

 ...

 [[  7   8  14]
  [  7   8  14]
  [  7   8  14]
  ...
  [ 64  68  74]
  [ 64  68  74]
  [ 64  68  74]]

 [[  7   8  14]
  [  7   8  14]
  [  7   8  14]
  ...
  [ 64  68  74]
  [ 64  68  74]
  [ 64  68  74]]

 [[  7   8  14]
  [  7   8  14]
  [  7   8  14]
  ...
  [ 64  68  74]
  [ 64  68  74]
  [ 63  69  74]]]


In [33]:
reducedIm = np.zeros_like(imArray)
for i in range(imArray.shape[0]):
    for j in range(imArray.shape[1]):
        reducedIm[i][j] = (imArray[i][j][0] + imArray[i][j][1] + imArray[i][j][2])/3
reducedIm = reducedIm[:, :, 0]
print("Successfully constructed brightness array!")
print("Brightness Array Dimensions: ", reducedIm.shape)
print(reducedIm)

Successfully constructed brightness array!
Brightness Array Dimensions:  (480, 640)
[[ 82  82  82 ... 145 144 144]
 [ 82  82  83 ... 145 144 144]
 [ 82  83  83 ... 145 145 144]
 ...
 [  9   9   9 ...  68  68  68]
 [  9   9   9 ...  68  68  68]
 [  9   9   9 ...  68  68  68]]


In [34]:
charSpectrum = "`^\",:;Il!i~+_-?][}{1)(|\\/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$"
len(charSpectrum)

65

In [49]:
charArray = np.empty(reducedIm.shape, dtype=str)
for i in range(reducedIm.shape[0]):
    for j in range(reducedIm.shape[1]):
        index = min(int(math.ceil(reducedIm[i][j] / 255 * 65)), 64)
        charArray[i][j] = charSpectrum[index]
print("Successfully constructed ASCII character array!")
print("ASCII Array Dimensions: ", charArray.shape)
print(charArray)

Successfully constructed ASCII character array!
ASCII Array Dimensions:  (480, 640)
[['(' '(' '(' ... 'U' 'U' 'U']
 ['(' '(' '|' ... 'U' 'U' 'U']
 ['(' '|' '|' ... 'U' 'U' 'U']
 ...
 [',' ',' ',' ... '{' '{' '{']
 [',' ',' ',' ... '{' '{' '{']
 [',' ',' ',' ... '{' '{' '{']]


In [50]:
for row in charArray:
    print("".join(row))

(((|///\\\\\\\\\\\\\\\\\|||||(((1111))))))))((((((((????]]]]iiiiJJJJ0000UUYYCCCCXXXXXXXXXXYY0000CCCCUUJUUUUUQQQLqqqpCCCCXXXXQQQQUUUUXXXXXXXXCCCCUUUUYYXYzXXXXXXXXzzzzzzzXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXzzzzzzzzzzzzXXXXYYYYXXXXXXXXYYYYXXXXccccccccccccXXXXYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYYYcccczzzzccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccUUUU
((||///\\\\|\\\\\\\\\\\\|||||(((1111))))))))((((((((????]]]]iiiiJJJJ0000UUYYCCCCXXXXXXXXXXYY0000CCCCUUUUUUUUQQLLqqqpCCCCXXXXQQQQUUUUXXXXXXXXCCCCUUUUYYXYzXXXXXXXzzzzzzzzXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXzzzzzzzzzzzzXXXXYYYYXXXXXXXXYYYYXXXXccccccccccccXXXXYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX